public Account {
        public string MySampleeTest{get;set;}
      


        public string Test1 ='Chanchal';
        public string Test2 = 'Kkumar';
     public string Test4 = 'Mathura';
        public string Test3 = 'BWG';

        public string Test1 ='ANurag';
        public string Test2 = 'Srivastava';
        public string Test4 = 'Allahabad';
        public string Test3 = 'Algoworks';
        public string Test1 ='Vedant';
        public string Test2 = 'Singh';
        public string Test3 = 'Wipro';
}
